env:
  es6:     true
  browser: true
  node:    true
extends:
  - eslint:recommended
  - plugin:vue/essential
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: 0
  no-var: 2
  strict: 0
  indent:
    - error
    - tab
  semi:
    - error
    - never

